# Welcome to Jekyll!
#

# Site settings
title: FoodPool
subtitle: We donate 10% or more of all our pool owner profit to Action Against Hunger!
description: Ending world hunger while earning rewards
owner: FoodPool # or company name
first_published: 2021 # if migrating another site, the year of your first publish
email: info@foodpool.online
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://foodpool.online" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/CardanoFood
  github: https://github.com/FoodPoolCardano
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
